### PR TITLE
Install LDC compiler

### PR DESCRIPTION
**Pull request by JohanEngelen**
This installs LDC 0.17.2 and LDC 1.0.0 (D compiler).
One of the steps to get LDC on https://d.godbolt.org/.

Thanks!

LDC can be found here: https://github.com/ldc-developers/ldc/releases

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Thanks! I'll merge now, and start updating the compilers available to CE

**Comment by mattgodbolt** [comment]
Looks like do_strip breaks all the executables in this case; will try without.

**Comment by JohanEngelen** [comment]
@mattgodbolt Wow, amazingly quick response!
Pointers to other places where LDC needs to be added are welcome :) 
Currently looking at: https://github.com/mattgodbolt/gcc-explorer/blob/master/etc/config/d.amazon.properties

I'm afraid some compile flags are a little different for LDC... Importantly:  `-of <filename>` instead of `-o <filename`. How hard is it to work with that?

**Comment by mattgodbolt** [comment]
Thanks! ldc might need special casing rather like '6g' (for go) does. Presumably it doesn't support `-S` ? In general I use the compiler's asm output instead of actually outputting a binary. The code to do this is in https://github.com/mattgodbolt/gcc-explorer/blob/master/lib/compile.js#L270 - but as you can see the way it's written doesn't make it very scalable for different compilers.

If you can get an example command line for how ideally you'd process a D file into assembly, let me know and I can see how it might fit in!

**Comment by JohanEngelen** [comment]
`ldc2 -c -output-s source_code.d -of assembly_code.s`

`-g` adds line information

**Comment by mattgodbolt** [comment]
perfect! for now, try hacking it locally to supply `-of` on line ~270ish of `compile.js` and see if everything looks like it's ok. add the ldc compiler path in your own `d.<hostname>.properties` file (or hack the `d.defaults.properties` -- if it all looks good then a very simple change should do it :)

**Comment by JohanEngelen** [comment]
(I am actually editing gcc-explorer files online ;)  haven't even tried running things locally yet)

**Comment by JohanEngelen** [comment]
@mattgodbolt It works with these changes :)  (only colourising doesn't work)
```diff
-            compileToAsm = compilerProps("compileToAsm", "-S").split(" ");
+            compileToAsm = compilerProps("compileToAsm", "-output-s").split(" ");
         } else {
             compileToAsm = compilerProps("compileToBinary", "").split(" ");
         }
         if (compilerInfo.isCl) {
             options = options.concat(['/c', '/Fa' + outputFilename, '/Fo' + outputFilename + ".obj"]);
         } else {
-            options = options.concat(['-g', '-o', outputFilename]);
+            options = options.concat(['-g', '-of', outputFilename]);
```

**Comment by mattgodbolt** [comment]
Awesome. If you feel up to making a full patch I'd be very happy to merge;
else I'll look at making the changes myself over the next few days

**Comment by JohanEngelen** [comment]
https://github.com/mattgodbolt/gcc-explorer/pull/157

**Pull request merged**
