### PR TITLE
--enable-languges=all

### PR DESCRIPTION
**Pull request by JesseTG**
Probably not sufficient to fully support all gcc languages.  Or maybe I'm wrong?  Is there an easy way you can test this?

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Hi Jesse; thanks for the patch! Unfortunately the majority of compilers aren't built by this script, I'm ashamed to say. I'll need to also set up more amazon instances, DNS entries and whatnot. I'm happy to do so: what languages were you thinking of?

**Comment by JesseTG** [comment]
If held at gunpoint I'd say Java, but that's just because I already know 
it.  Honestly, the only reason I filed this is in the first place 
because I thought it might be quick to set up, but apparently not!

**Comment by mattgodbolt** [comment]
I see. D, Rust and Go are already supported (https://d.godbolt.org/
https://rust.godbolt.org/ and https://go.godbolt.org respectively).

Java doesn't compile into object code directly, so there's nothing really
to show, but there's a similar project for Java at
http://javabytes.herokuapp.com/

Also see https://github.com/mattgodbolt/gcc-explorer/issues/12 which tracks
a number of similar requests.

Cheers, Matt :)

**Comment by JesseTG** [comment]
Wait, I thought Java could be compiled into native code through `gcj`?

**Comment by mattgodbolt** [comment]
You're absolutely right; I had no idea gcj was an ahead-of-time compiler!
Thanks!

**Comment by mattgodbolt** [comment]
Closing: it would take more than rebuilding all the compilers here to get the other languages in. Sorry this was left open so long.

**Pull request closed without merging**
